/**
 * Types for equity advice data structures
 */

/**
 * @typedef {Object} EquityInsight
 * @property {string} type - Type of insight (diversification, tax, liquidity, retirement, etc.)
 * @property {string} title - Brief title of the insight
 * @property {string} content - Detailed explanation of the insight
 * @property {string} priority - Priority level (high, medium, low)
 */

/**
 * @typedef {Object} EquityAdvice
 * @property {Array<EquityInsight>} insights - Array of insights about the equity portfolio
 * @property {string} summary - Summary of the overall advice
 * @property {Array<string>} recommendedActions - List of actionable recommendations
 * @property {boolean} [powered_by_claude] - Flag indicating if the advice was generated by Claude AI
 */

/**
 * @typedef {Object} ScenarioAdvice
 * @property {Array<Object>} insights - Array of insights specific to the scenario
 * @property {string} summary - Summary of the scenario analysis
 * @property {Array<string>} recommendations - List of recommendations for the scenario
 */

// Export as needed for TypeScript support
export const AdviceTypes = {
  GENERAL: 'general',
  DIVERSIFICATION: 'diversification',
  TAX: 'tax',
  LIQUIDITY: 'liquidity',
  RETIREMENT: 'retirement',
  DEBT: 'debt',
  RISK: 'risk',
  EARLY_EXERCISE: 'earlyExercise',
  EXPIRATION: 'expiration'
};

export const PriorityLevels = {
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low'
};